config:
  # Language
  lang: en

  # Your namespace
  namespace: "nameplates"

  # Font Name
  # Recommended not to set "default" when you are using "minecraft" as your namespace.
  # You can use font like "nameplate" instead.
  font: "default"

  # Customize the folder where png files should be generated.
  # This is useful for those who want to keep their resource pack structure in order.
  folder-path: 'font\nameplates\'

  # The initial character of all nameplates.
  # 뀁 is the first character of Korean \ub001.
  # You can specify any Unicode Character as you want.
  start-char: '뀁'

  # The duration (in seconds) that the nameplate preview will last for.
  preview-duration: 5

  # The default nameplate.
  # "none" represents no default nameplate.
  default-nameplate: 'none'

  # Recommended to keep this true, otherwise players may see weird characters
  # above their heads if they have not accepted the resource pack.
  # This option supports proxy when using Mysql
  show-after-load-resourcepack: true

  # Placeholder based prefix and suffix system. When enabled, it is recommended
  # to use PlaceholderAPI to be able to use this feature to the fullest extent.
  # keep it empty if you don't want to enable this feature.
  prefix: ''
  suffix: ''

  # Thin-font support
  use-thin-font: false

  # Should the plugin hook into other plugins
  integrations:
    # When enabled, the plugin will be able to parse prefix and suffix
    PlaceholderAPI: false
    # When enabled, the plugin will automatically place the nameplates
    # folder into the resource pack generated by ItemsAdder.
    ItemsAdder: false