# Do not change
config-version: '6'

settings:
  # Valid Options: SQLite MYSQL
  # Only MYSQL supports pool.
  # Restart is a must when you change database configuration.
  storage-mode: SQLite
  use-pool: false
  disable-async: false
  # If you are updating from a version lower than 2.0-PRE-6
  # Enable this to migrate data! If you are using MySQL you only need one server to proceed migration
  # BackUp your data before enabling this!
  migration: false

# MySQL settings
MySQL:
  host: localhost
  port: 3306
  user: root
  password: password
  database: minecraft
  table-name: nameplates_data
  property:
    use-ssl: false
    encoding: utf8
    timezone: ''
    allowPublicKeyRetrieval: false

# Connection pool settings
Pool-Settings:
  maximum-pool-size: 10
  minimum-idle: 10
  maximum-lifetime: 180000
  idle-timeout: 60000