name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.17
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
softdepend:
  - ItemsAdder
  - PlaceholderAPI
  - TAB
  - Oraxen
commands:
  customnameplates:
    usage: /customnameplates
    aliases:
      - nameplates
  chatbubbles:
    usage: /chatbubbles
    aliases:
      - bubbles

permissions:
  nameplates.*:
    description: Gives access to all nameplates commands
    children:
      nameplates.generate: true
      nameplates.reload: true
      nameplates.forceequip: true
      nameplates.forceunequip: true
      nameplates.help: true
      nameplates.unequip: true
      nameplates.preview: true
      nameplates.list: true

  nameplates.generate:
    default: op
  nameplates.reload:
    default: op
  nameplates.forceequip:
    default: op
  nameplates.forceunequip:
    default: op
  nameplates.help:
    default: op
  nameplates.unequip:
    default: true
  nameplates.preview:
    default: true
  nameplates.list:
    default: true
  nameplates.equip:
    default: true