name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.CustomNameplates
api-version: 1.16
authors: [ XiaoMoMi ]
depend:
  - ProtocolLib
softdepend:
  - ItemsAdder
  - PlaceholderAPI
commands:
  customnameplates:
    usage: /customnameplates help
    aliases:
      - nameplates