# Player can only receive at most 1 actionbar at the same time
actionbar:
  check-frequency: 10
  conditions:
    permission: "actionbar.show"
  text-display-order:
    1:
      # Measured in ticks
      duration: 1000
      # Text content
      text: '%nameplates_conditional_actionbar%'
      # The frequency of refreshing the text, the lower the value is, the faster the placeholders are updated
      # measured in ticks, -1 = disable refreshing
      refresh-frequency: 1