# Team / Unlimited / Disable
mode: TEAM

# The duration (in seconds) that the nameplate preview will last for.
preview-duration: 5

# Default nameplate to display if player's nameplate is "none"
default-nameplate: 'none'

# This decides what %nameplates_prefix/suffix% would return
nameplate:
  refresh-frequency: 10
  prefix: ''
  player-name: '%player_name%'
  suffix: ''
  # Disable this if you are using a custom Tab plugin
  fix-Tab: true

# Settings for Team mode
team:
  # measured in ticks
  refresh-frequency: 10
  prefix: '%nameplates_prefix%'
  suffix: '%nameplates_suffix%'

# Settings for Unlimited mode
unlimited:
  tag_1:
    text: '%nameplates_nametag%'
    vertical-offset: -1
    owner-conditions:
      potion-effect: "INVISIBILITY=0"
    viewer-conditions: { }
  tag_2:
    text: "IP: %player_ip%  My IP: %viewer_player_ip%"
    vertical-offset: -0.7
    refresh-frequency: 10
    check-frequency: 20
    owner-conditions:
      potion-effect: "INVISIBILITY=0"
    viewer-conditions:
      condition_1:
        type: permission
        value: 'nameplates.admin'