name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.paper.CustomNameplatesPluginImpl
api-version: 1.17
authors: [ XiaoMoMi ]
folia-supported: true
depend: [ ProtocolLib ,PlaceholderAPI ]