name: CustomNameplates
version: '${version}'
main: net.momirealms.customnameplates.paper.CustomNameplatesPluginImpl
api-version: 1.17
authors: [ XiaoMoMi ]
folia-supported: true
depend: [ ProtocolLib ,PlaceholderAPI ]
softdepend: [ MagicCosmetics, TAB, CMI, TrChat, ItemsAdder, Oraxen ]
permissions:
  nameplates.*:
    description: Gives access to all nameplate user commands
    children:
      nameplates.equip: true
      nameplates.unequip: true
      nameplates.preview: true
      nameplates.list: true
  nameplates.equip:
    default: true
  nameplates.unequip:
    default: true
  nameplates.preview:
    default: true
  nameplates.list:
    default: true
  customnameplates.admin:
    default: op

  bubbles.*:
    description: Gives access to bubble all user commands
    children:
      bubbles.equip: true
      bubbles.unequip: true
      bubbles.list: true
  bubbles.equip:
    default: true
  bubbles.unequip:
    default: true
  bubbles.list:
    default: true